version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus-dev
    ports:
      - 9090:9090
    volumes:
      - ./src/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    
  grafana:
    image: grafana/grafana-oss
    container_name: grafana-dev
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource